```{r Load Libraries}

library(plyr)
library(dplyr)
library(ggplot2)
library(highcharter)
library(ggmap)
library(lubridate)
library(leaflet)
library(leaflet.extras)

```

```{r Leaflet Map with Circle Markers, echo=FALSE, message=FALSE, warning=FALSE}




map <- 
leaflet() %>% 
  setView(lng = -86.6, 
          lat = 14.63, 
          zoom = 8) %>% 
  
  addProviderTiles("Esri.WorldStreetMap") %>% 
  addCircleMarkers(
  lat = protestas$lat,
  lng = protestas$lon,
  radius = (as.numeric(protestas$size*2)),
  
  #stroke = FALSE,
 color = "#de2d26"
  #fillOpacity = 0.6
)

map

```


```{r Leaflet Heatmap con las 595 Protestas}

protestas <- read.csv("data/protestasconcoords.csv")


protestas$lon[is.na(protestas$lon)] <- "-75"
protestas$lat[is.na(protestas$lat)] <- "6.9"

protestas$lon <- as.numeric(protestas$lon)
protestas$lat <- as.numeric(protestas$lat)




leaflet(protestas) %>% 
  setView(lng = -86.6, 
          lat = 14.63, 
          zoom = 8) %>% 
  
  addProviderTiles("Esri.WorldImagery") %>%
  
  addHeatmap(lng = ~lon, 
             lat = ~lat, 
             intensity = .5, 
             radius = 20
             

             )
  


#leaflet.extras::addHea

```



```{r}
protestas <- read.csv("data/protestasconcoords.csv")


protestas$lon[is.na(protestas$lon)] <- "-75"
protestas$lat[is.na(protestas$lat)] <- "6.9"

protestas$lon <- as.numeric(protestas$lon)
protestas$lat <- as.numeric(protestas$lat)




leaflet(protestas) %>% 
  setView(lng = -86.6, 
          lat = 14.63, 
          zoom = 8) %>% 
  
  addProviderTiles("Esri.WorldImagery") %>%
  
  addWebGLHeatmap(lng = ~lon, 
             lat = ~lat, 
             intensity = .4, 
             size = 10000
             )


sisters of mercy have been in contact
```















